### PR TITLE
Release candidate

### PR DESCRIPTION
**Pull request by smittytone**

### CODE REVIEW

**Comment by smittytone** [comment]
I've remove the __firmware_ var and just passed the blob straight through to __init()_ as suggested. You're absolutely right: there's no need to keep this hanging around once it's been used.

**Review by betzrhodes — APPROVED** [review]
Code looks good. Should this be a pre-release (version < 1.0.0) since it doesn't have tests or examples

**Comment by smittytone** [comment]
The key example is here, https://github.com/electricimp/BluetoothBlinkUp, so I'll add a reference to that. I'm not sure what worthwhile tests can be run since it requires external gadgetry, ie. a phone or simulation of one to send the BLE connection requests. In as much as it works with the above example, it's been tested, I guess.

**Comment by betzrhodes** [comment]
> The key example is here, https://github.com/electricimp/BluetoothBlinkUp, so I'll add a reference to that. I'm not sure what worthwhile tests can be run since it requires external gadgetry, ie. a phone or simulation of one to send the BLE connection requests. In as much as it works with the above example, it's been tested, I guess.

I guess what I'm looking for is some way for me to easily verify that the code here is running as intended before I release it as a library. We have far too many libraries with issues, and I'd like some way to test library code before releasing it. That can either be through an example or tests. The example you are pointing at is not using this exact code yet.

**Comment by smittytone** [comment]
Look in the [btlelib_example_test branch](https://github.com/electricimp/BluetoothBlinkUp/tree/btlelib_example_test). This is a version with the BTLEBlinkUp library pasted in.
The develop branch is set up to use the library when it's published (so can't be switched to master until it is).
I have confirmed that the code works with the example (which also contains my Bluetooth BlinkUp iOS app)

**Pull request merged**
